### ISSUE TITLE
question about project setup with nix

### ISSUE THREAD

**Issue by willbush** [Vodurden/CrossyToad#2]
Hi, thanks for making this project in the open. I just have some questions about
how you setup the project with nix and if there's anything you could share about
that process.

I have been following the guides:

 - https://github.com/Gabriel439/haskell-nix
 - https://cah6.github.io/technology/nix-haskell-1/
 - https://cah6.github.io/technology/nix-haskell-2/
 - https://www.haskell.org/cabal/users-guide/nix-integration.html
 - https://www.fosskers.ca/blog/nix-en.html

I ran across your project when looking for examples to setup `.dir-locals.el`
with `nix-shell`. I was surprised to see you have your project setup exactly how
I am learning how to do as well (with nix). I also noticed your `ADR` files,
which is cool. I never heard of architecture decision record documents before,
but I love the idea.

I noticed that you decided to use `direnv`, which I have been playing with and
got to work, but I was wondering why you decided to use `nix-shell` in your
`dir-locals.el` file, and if there was any downside to using `direnv` vs
`nix-shell`.

**Comment by Vodurden** [comment]
Hi @willbush, great question!

When I first set up this project I just used `nix-shell` and `cabal new-build` to compile it in the correct environment. 

However I had a problem: My text editor (in this case `emacs`) couldn't find all my Haskell libraries because it wasn't run in the same `nix-shell`. I searched for a number of solutions and finally settled on an approach using `direnv`.

The trick is:

- `direnv` has nix support
- `emacs` has `direnv` support

So if I set up `direnv` to load my nix shell, and I set up emacs to use `direnv` then suddenly `emacs` is aware of the correct environment and everything works!

That's why I'm using `direnv` to load a `nix-shell` \:)

**Comment by willbush** [comment]
Ah yes it seems quite nice. I kinda wish I could tell it manually what to load instead of it doing so automatically based on `.envrc` files because I like to jump around through the file system with emacs and don't want it loading/unloading all the time. I might make a feature request with the package maintainer. Thanks for your input.
